### PR TITLE
Update settings.json

### PR DESCRIPTION
**Pull request by g9militantsYT**

### CODE REVIEW

**Comment by lucsoft** [comment]
Is this an extra plugin?

**Comment by GregTCLTK** [comment]
package lock??

**Comment by lucsoft** [comment]
@g9militantsYT install deno from https://deno.com/

**Comment by g9militantsYT** [comment]
Tq

**Comment by g9militantsYT** [comment]
> @g9militantsYT install deno from https://deno.com/

K

**Comment by g9militantsYT** [comment]
> @g9militantsYT install deno from https://deno.com/

Wait I did it earlier. Didn't work

**Comment by GregTCLTK** [comment]
> Calm down idk what I'm doing.. just tinkering for now
Then don't open a pr?

**Pull request closed without merging**
